<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Categories;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository implements ICategoriesRepository
{
    public function invokeFindByBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder($this->getClassMetadata()->getTableName());
    }

    /**
     * @param string $name
     * @return null|object
     */
    public function findByCategoryName(string $name)
    {
        return $this->findOneBy(['name' => $name]);
    }
}
