<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository implements ICommentsRepository
{
    /**
     * @return QueryBuilder
     */
    public function getCommentsOnCertainUser(): QueryBuilder
    {
        // TODO: Implement getCommentsOnCertainUser() method.
    }

    /**
     * @return QueryBuilder
     */
    public function getCommentOnCertainProduct(): QueryBuilder
    {
        // TODO: Implement getCommentOnCertainProduct() method.
    }

    public function invokeFindByBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder($this->getClassMetadata()->getTableName());
    }
}
