<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Categories;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository implements IProductRepository
{
    public function invokeFindByBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder($this->getClassMetadata()->getTableName());
    }

    /**
     * @param string $name
     * @return array
     */
    public function getProductsByCategory(string $name): array
    {
        /* @var Categories $category */
        $category = $this->getEntityManager()->getRepository(Categories::class)->findByCategoryName($name);
        return $this->findBy(['category' => $category->getId()]);
    }
}
