<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository implements IPromotionRepository
{
    /**
     * @return QueryBuilder
     */
    public function getActivePromotions(): QueryBuilder
    {
        // TODO: Implement getActivePromotions() method.
    }

    /**
     * @return QueryBuilder
     */
    public function getAllPromotions(): QueryBuilder
    {
        // TODO: Implement getAllPromotions() method.
    }

    /**
     * @return QueryBuilder
     */
    public function getPromotionByInterval(): QueryBuilder
    {
        // TODO: Implement getPromotionByInterval() method.
    }

    public function invokeFindByBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder($this->getClassMetadata()->getTableName());
    }
}
