<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Promotion;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository implements IPromotionRepository
{
    public function invokeFindByBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder($this->getClassMetadata()->getTableName());
    }

    /**
     * @param Promotion $promotion
     * @return bool
     */
    public function addPromotionForProducts(Promotion $promotion): bool
    {
        $em = $this->getEntityManager();
        $promotion->setCategory(null);
        $em->persist($promotion);

        if (true === $em->getUnitOfWork()->isScheduledForInsert($promotion)) {
            $em->flush();
            return true;
        }

        return false;
    }

    /**
     * @return array
     */
    public function getActivePromotions(): array
    {
        return $this->getEntityManager()
                    ->getRepository(Promotion::class)
                    ->findAll();
    }

    /**
     * @return array
     */
    public function getAllPromotions(): array
    {
        // TODO: Implement getAllPromotions() method.
    }

    /**
     * @return null|Promotion
     */
    public function getPromotionByInterval()
    {
        // TODO: Implement getPromotionByInterval() method.
    }

    /**
     * @param int $promotionID
     * @return null|Promotion
     */
    public function getPromotionByID(int $promotionID)
    {
        $stmt = $this->getEntityManager()
                     ->getRepository(Promotion::class)
                     ->createQueryBuilder('promotion')
                     ->where('promotion.id = :promotionID')
                     ->setParameter('promotionID', $promotionID);

        return $stmt->getQuery()
                    ->getOneOrNullResult();
    }
}
