security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:   ROLE_USER
        ROLE_ADMIN:  ROLE_ADMIN
        ROLE_EDITOR: ROLE_EDITOR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                post_only: true
                always_use_default_target_path: true
                default_target_path: allProducts
            logout:
                path: fos_user_security_logout
            anonymous:    true
            remember_me:
                secret:      "%secret%"

    access_control:
        - { path: ^/login$, allow_if: "not has_role('ROLE_USER')" }
        - { path: /register, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }